config/routes.rb
Rails.application.routes.draw do
  resources :imagetags
  resources :hashtags
  resources :images  
  resources :comments
  resources :users, only: [:new, :create, :index, :show, :edit, :update]
  resources :sessions, only: [:new, :create]
  delete "/sessions", to: "sessions#destroy", as: "log_out"
  resources :comments, only: [:index, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :image
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
  has_many :image_tags
  has_many :images, through: :image_tags
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :imagetags
  has_many :hashtags, through: :imagetags
end

app/models/imagetag.rb
class Imagetag < ApplicationRecord
  belongs_to :image
  belongs_to :hashtag

  def hash_tag
  end


end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :comments
  has_many :images
  


  validates :username, uniqueness: true, presence: true
  validates :email, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   helper_method :current_user

 def log_in_user(user)
   session[:user_id] = user.id
 end

 def log_out
   session[:user_id] = nil
 end

 def logged_in_user_id
   session[:user_id]
 end

 def logged_in?
   !!logged_in_user_id
 end

 def authorized?(user_id)
   logged_in_user_id == user_id
 end

 private

 def current_user
   @current_user ||= User.find(session[:user_id]) if session[:user_id]
 end




end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

 def index
     @user = User.find(params[:user_id])
     @image = Image.find(params[:image_id])
     @comments = Comment.all
 end

 def show
     @comment = Comment.find(params[:id])
 end

 def new
     @user = User.find(params[:user_id])
     @image = Image.find(params[:user_id])
     @comment = Comment.new

 end

 def create
     @comment = Comment.create(comment_params)
     @comment.save
     redirect_to image_path(:image_id, @comment)
 end

 def edit
 end

 private

 def comment_params
     params.require(:comment).permit(:user_id, :image_id, :content)
 end

end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController


 def index
     @hashtags = Hashtag.all
 end

 def show
     @hashtag = Hashtag.find(params[:id])
     @images = Image.all
 end

 def new
     @hashtag = Hashtag.new

 end

 def create
     @hashtag = Hashtag.create(hashtag_params)
     @hashtag.save
     redirect_to hashtag_path(@hashtag)
 end

 def edit
 end

 private

 def hashtag_params
     params.require(:hashtag).permit(:name)
 end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
before_action :current_user, only:[:create, :edit]

 def index

     @users = User.all
     @images = Image.all

 end

 def show
     @image = Image.find(params[:id])
 end

 def new
     @image = Image.new
 end

  def create

    current_user.images.create(image_params)
     image = Image.create(image_params)
     redirect_to image
   end

 def edit
   @image = Image.find(params[:id])
   # if !authorized?(@image.user)
   #   redirect_to new_session_path()
  # end
 end

 def update
   @image = Image.find(params[:id])
   if @image.update(image_params)
     redirect_to images_path
   else
     render :edit
   end
 end

 private

 def image_params
     params.require(:image).permit(:title, :img_url, :hashtag_id)
 end

end

app/controllers/imagetags_controller.rb
class ImagetagsController < ApplicationController

def new
 @imagetag  = Imagetag.new
end

def index
  @imagetags =  Imagetag.all
end

def show
 @imagetag = Imagetag.find(params[:id])
end

def create
@imagetag = Imagetag.create(imagetag_params)
redirect_to users_path
end

private

  def imagetag_params
    params.require(:imagetag).permit(:image_id, :hashtag_id )
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def image
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      log_in_user(@user)
      redirect_to images_path
    else
      flash[:errors] = [ "Username or password didn't match" ]
      redirect_to new_session_path
    end
  end

  def destroy
    log_out
    redirect_to images_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render :new
    end
  end

  def authenticate(password)
    BCrypt::Password.new(@user.password_digest) == password
  end





  private

  def user_params
    params.require(:user).permit(:name, :email, :username, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/hashtags_helper.rb
module HashtagsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/imagetags_helper.rb
module ImagetagsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.erb
<% form_for @user do |f|%>
<%= f.label :name %>
<%= f.text_field :name %></br>


<%= f.label :email %>
<%= f.text_field :email %></br>

<%= f.label :username %>
<%= f.text_field :username %></br>

<%= f.label :password %>
<%= f.password_field :password %>
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>
<%= f.submit "Sign Up!" %>
<%= f.submit 'Back', :back %>
<% end %>

app/views/comments/edit.erb
Edit page for an object

app/views/comments/index.erb
Index page for comments

app/views/comments/new.erb
New page ...for comments

app/views/comments/show.erb
Show page for Comments

app/views/images/_form.erb
<style>
body {
  background-image: url('https://media.giphy.com/media/t6conLiC13yyaqgijR/giphy.gif');
  background-size: cover;
}

</style>

<%= form_for(@image) do |f| %>
<ul>
<li>
   <%=f.label :title %>
   <%=f.text_field :title %>
</li>
<li>
   <%=f.label :img_url %>
   <%=f.text_area :img_url %>

</li>
   <%=f.submit "Submit"%>
</ul>
<%end%>

app/views/images/edit.erb
<%= render 'form' %>

app/views/images/index.erb
Images index page for all image

app/views/images/index.html.erb
<h1>Welcome</h1>
<% if current_user %>
  Logged in as <%= current_user.email %>.
<% else %>
  <%= link_to "Sign Up", new_user_path %> or
  <%= link_to "Log In", new_session_path %>
<% end %>
<!DOCTYPE html>
<html>
<head>

<style>
body {
  background-image: url('https://media.giphy.com/media/t6conLiC13yyaqgijR/giphy.gif');
  background-size: cover;
}

</style>
</head>
<body>
<h1>Images</h1>
  <% @images.each do |image|  %>
  Title: <%= image.title %><br>
  <img src=<%=image.img_url%>>
  <% end %>




<%= form_tag log_out_path, method: "delete" do%>
<%= submit_tag 'Log Out' %><br>
<button type="button" name="button"><%= link_to "Create Image", new_image_path %></button>
<% end %>
</body>

</html>

app/views/images/new.erb
<%= render 'form' %>

app/views/images/show.erb
Images Show Page

<ul>

  <li><%= @image.title %></li><br>
  <li><%= image_tag "#{@image.img_url}", style: 'height:20%:width:20%' %></li><br>



</ul>

app/views/imagetags/index.erb
<style>
body {
  background-image: url('https://media.giphy.com/media/t6conLiC13yyaqgijR/giphy.gif');
  background-size: cover;
}

</style>

<h1>Imagetag index page</h1>

app/views/imagetags/index.html.erb
Index for Image tags page

app/views/imagetags/new.erb
<style>
body {
  background-image: url('https://media.giphy.com/media/t6conLiC13yyaqgijR/giphy.gif');
  background-size: cover;
}

</style>

<%= form_for @imagetag do |f| %>
<%= f.label :Image %>
<%= f.collection_select :image, Image.all, :id, :title  %>
<%= f.label :Hashtag %>
<%= f.collection_select :hashtag, Hashtag.all, :id, :name  %>
<%= f.submit %>
<% end %>

app/views/imagetags/show.erb
<%= @imagetag. %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {box-sizing: border-box;}
body {
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
}
.header {
  overflow: hidden;
  background-color: #80bdff;
  padding: 20px 10px;
}
.header a {
  float: left;
  color: #4a4848;
  text-align: center;
  padding: 12px;
  text-decoration: none;
  font-size: 18px;
  line-height: 25px;
  border-radius: 4px;
}
.header a.logo {
  font-size: 25px;
  font-weight: bold;

}
.header a:hover {
  background-color: #ddd;
  color: black;
}
.header a.active {
  background-color: dodgerblue;
  color: white;
}
.header-right {
  float: right;
}
@media screen and (max-width: 500px) {
  .header a {
    float: none;
    display: block;
    text-align: left;
  }
  .header-right {
    float: none;
  }
}
</style>
</head>
<body>
<div class="header">
  <a href="http://localhost:3000/images" class="logo">Instagram Lite</a>
  <div class="header-right">

    <a class="active" href="/sessions/new">Login</a>

    <a href="http://localhost:3000/users/new">Register</a>
    <a class="header" href="http://localhost:3000/images/new">Upload Image</a>
  <%=link_to "Back", :back  %>
  </div>
</div>
<div style="padding-left:20px">
</div>
</body>
</html>

<%= yield %>

app/views/layouts/footer.html.erb
footer

app/views/users/_form.erb
<%=form_for @user do |f|%>
<p>
    <%=f.label :name%>
    <%=f.text_field :name %>
</p>

<p>
    <%=f.label :email%>
    <%=f.text_field :email %>
</p>

<p>
    <%=f.label :username%>
    <%=f.text_field :username %>
</p>

<p>
    <%=f.label :password%>
    <%=f.password_field :password %>
</p>

<%=f.submit  %>
<%end%>

app/views/users/index.erb
<style>
body {
  background-image: url('https://media.giphy.com/media/t6conLiC13yyaqgijR/giphy.gif');
  background-size: cover;
}

</style>

<h1>This is the User's index page.</h1>
<ol>
<% @users.each do |user| %>
<li><%= link_to(user.name, user_path(user))%></li>
<% end %>
</ol>

app/views/users/new.erb
<style>
body {
  background-image: url('https://media.giphy.com/media/t6conLiC13yyaqgijR/giphy.gif');
  background-size: cover;
}

</style>
<div class="userform">
<%= render 'form' %>
</div>

app/views/users/show.erb
<style>
body {
  background-image: url('https://media.giphy.com/media/t6conLiC13yyaqgijR/giphy.gif');
  background-size: cover;
}

</style>

<%= @user.name %>
<br>
<% @user.images.each do |image|%>
<%= image.title %>
<%= image_tag "#{image.img_url}", style: 'height:10%;width:10;'  %>
<% image.hashtags.each do |tag|%>
<%= tag.name %>


<%image.comments.each do |comment| %>

Comments:<%= comment.content %>
<% end %>
<% end %>
<% end %>